spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todaymind?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



clova:
  completion-url: http://localhost:8080/dummy
  api-key: dummy_key
  api-key-id: dummy_id

jwt:
  access-token:
    expire-time: PT1H  # 1시간
  refresh-token:
    expire-time: P14D  # 14일
  secret-key: d29vd29uLXVubmllLWZpZ2h0aW5nLXRvZGF5LW1pbmQtcHJvamVjdC1zZWNyZXQta2V5