spring:
  application:
    name: today-mind-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    com.example.todaymindserver: info
    org.hibernate.sql: off
    org.hibernate.type.descriptor.sql: off

oauth:
  kakao:
    user-info-url: https://kapi.kakao.com/v2/user/me
  google:
    user-info-url: https://openidconnect.googleapis.com/v1/userinfo

jwt:
  access-token:
    expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token:
    expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}
  secret-key: ${JWT_SECRET_KEY}

clova:
  completion-url: ${CLOVA_COMPLETION_URL}
  api-key: ${CLOVA_API_KEY}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

scheduler:
  refresh-token:
    cleanup:
      cron: "0 0 3 * * *"

management:
  endpoints:
    web:
      exposure:
        include: health