spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todaymind?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 변경 시 DB 테이블 자동 업데이트
    show-sql: true # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL 로그를 보기 좋게 포맷팅


clova:
  completion-url: http://localhost:8080/dummy
  api-key: dummy_key_for_local_testing
  api-key-id: dummy_id_for_local_testing

jwt:
  access-token:
    expire-time: PT1H  # 1시간
  refresh-token:
    expire-time: P14D  # 14일
  # 보안을 위해 충분히 긴 시크릿 키 유지
  secret-key: d29vd29uLXVubmllLWZpZ2h0aW5nLXRvZGF5LW1pbmQtcHJvamVjdC1zZWNyZXQta2V5